# Makefile: A standard Makefile for __SOURCE_NAME__.c

CFLAGS=-g -std=gnu99 -Wall -Wno-parentheses
LDFLAGS=-lm

all  : __SOURCE_NAME__
clean:
	/bin/rm -rf __SOURCE_NAME__ __SOURCE_NAME__.o
# END OF FILE
